### PR TITLE
changing to require java 1.8 instead of 7

### PR DESCRIPTION
**Pull request by BusyByte**

### CODE REVIEW

**Comment by BusyByte** [comment]
resulting from comments on https://github.com/Banno/betamax/pull/7

**Comment by BusyByte** [comment]
retest this please

**Comment by DustinChaloupka** [comment]
:+1:

**Comment by rubbish** [comment]
:+1:

**Comment by BusyByte** [comment]
retest this please

**Comment by BusyByte** [comment]
retest this please

**Comment by BusyByte** [comment]
The build passed on this, not sure why it says 1 pending check for jenkins still?

**Comment by lamdor** [comment]
:+1:

**Comment by jwinder** [comment]
:+1:

**Pull request merged**
