### PR TITLE
Resolve issue with Apache HttpClient w/ HTTPS

### PR DESCRIPTION
**Pull request by bjhartin**
by upgrading the version of apache's httpcomponents used.  Also upgraded gradle and other library/plugin versions to be more current.

To test this, run "./gradlew clean test".  We don't yet have a PR build for this.

### CODE REVIEW

**Comment by lamdor** [comment]
This needs master merged into it. There's also some log files sticking around in the diff.

**Comment by bjhartin** [comment]
@rubbish You sure about the merge?  Master contains a lot of unreleased work that he hasn't touched in a long time.  Hasn't committed since June 2014.  I intentionally branched from the latest (1.1.2) release tag.

**Comment by adamdecaf** [comment]
@bjhartin This is pointed at master. Should it be pointed at a different tag?

**Comment by bjhartin** [comment]
@adamdecaf Closing and opening a PR against 1.1.2-banno.

**Pull request closed without merging**
