### PR TITLE
Adding ability to publish to local ivy repo via gradle.

### PR DESCRIPTION
**Pull request by bjhartin**
This didn't have the ability to publish locally.

### CODE REVIEW

**Comment by BusyByte** [comment]
:+1:

**Comment by adamdecaf** [comment]
:+1:

**Comment by BusyByte** [comment]
This is failing because it currently requires Java 7, is there any reason to require this version of Java anymore?

**Comment by adamdecaf** [comment]
@BusyByte Nah, we've upgraded everything to java 8.

**Comment by bjhartin** [comment]
@BusyByte At one point, there were test failures under JDK 1.7 due to the gradle/groovy versions or dependency versions.  However, it seems fine under JDK 1.8 now.

**Comment by BusyByte** [comment]
@bjhartin I think we are ok because I tested the core-fetch pr for enabling betamax with a Java 8 version.

**Pull request merged**
