### PR TITLE
Resolve issue with Apache HttpClient w/ HTTPS 

### PR DESCRIPTION
**Pull request by bjhartin**
by upgrading the version of apache's httpcomponents used. Also upgraded gradle and other library/plugin versions to be more current.

To test this, run "./gradlew clean test". We don't yet have a PR build for this.

### CODE REVIEW

**Comment by bjhartin** [comment]
@rubbish @adamdecaf

**Comment by adamdecaf** [comment]
@bjhartin I'm not totally sold on always trusting ssl certs here, even if it is just for testing. What was the use case again? Could we use a java [KeyStore](https://docs.oracle.com/javase/7/docs/api/java/security/KeyStore.html) instead?

**Comment by adamdecaf** [comment]
ok to test

**Comment by bjhartin** [comment]
@adamdecaf Yes, I think you're right.

**Pull request merged**
